import { DashboardSummary, PaymentRecord, DecisionRecord } from '../types';
import { mockHistoricalDecisionsList, createDecisionRecordFromPayment } from './mockDecisions';

export const mockDetailedPayments: PaymentRecord[] = [
  {
    id: 'pay_9F8aK29x',
    amount: 145000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent9201',
      customerName: 'Rahul Sharma',
      email: 'rahul.sharma@gmail.com',
      segment: 'Enterprise',
      lifetimeValue: 3840000,
      totalSuccessfulPayments: 142,
      totalFailedPayments: 4,
      historicalRecoveryRate: 0.92,
      avgRecoveryLatencyHours: 4.5,
      retryFatigueScore: 1.2,
    },
    paymentMethod: 'mandate',
    paymentMethodDetails: 'ICICI Corporate E-Mandate •••• 9012',
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    failedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    recoveryProbability: 0.88,
    expectedRecoveryValue: 127600,
    recommendedAction: 'retry_later',
    priority: 'critical',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'Customer operates on a bimonthly treasury settlement cycle. Historical settlement velocity indicates 92% recovery when execution is timed for 6 hours post-failure, staying strictly within the 72h policy retry boundary.',
    candidateActions: [
      {
        action: 'retry_later',
        label: 'Retry Later (6 hrs)',
        probability: 0.88,
        expectedRecovery: 127600,
        confidence: 0.94,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Optimal time window identified during afternoon liquidity clearing.',
      },
      {
        action: 'send_payment_link',
        label: 'Send Dynamic Payment Link',
        probability: 0.72,
        expectedRecovery: 104400,
        confidence: 0.86,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Viable secondary channel; creates minor treasury reconciliation friction.',
      },
      {
        action: 'send_reminder',
        label: 'Send WhatsApp / Email Reminder',
        probability: 0.65,
        expectedRecovery: 94250,
        confidence: 0.82,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Contact limit permits notification (0/2 notifications sent today).',
      },
      {
        action: 'retry_now',
        label: 'Retry Immediately',
        probability: 0.24,
        expectedRecovery: 34800,
        confidence: 0.91,
        isRecommended: false,
        policyStatus: 'restricted',
        policyNotes: 'Deprioritized: Immediate retry before settlement window yields 24% success and burns 1 retry quota.',
      },
      {
        action: 'request_payment_method_update',
        label: 'Request Payment Method Update',
        probability: 0.45,
        expectedRecovery: 65250,
        confidence: 0.78,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Unnecessary operational burden since mandate instrument is healthy.',
      },
      {
        action: 'escalate_to_human',
        label: 'Escalate to Dedicated RM',
        probability: 0.80,
        expectedRecovery: 116000,
        confidence: 0.75,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'High-touch escalation reserved as fallback if 6h scheduled retry fails.',
      },
      {
        action: 'stop_recovery',
        label: 'Stop Recovery (Abandon)',
        probability: 0.0,
        expectedRecovery: 0,
        confidence: 0.99,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Unwarranted for high-value Enterprise client with 92% historical recovery rate.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Retry Threshold Limit',
        description: 'Maximum permitted retries per billing cycle',
        status: 'passed',
        detail: '0 of 3 allowed retries consumed. Quota available.',
      },
      {
        id: 'rule_2',
        ruleName: 'Recovery Window Guardrail',
        description: '72-hour maximum active recovery period',
        status: 'passed',
        detail: 'Failure occurred 35 minutes ago. 71.4 hours remaining in active recovery window.',
      },
      {
        id: 'rule_3',
        ruleName: 'Customer Contact Frequency Limit',
        description: 'Maximum 2 outbound customer touchpoints in 24 hours',
        status: 'passed',
        detail: '0 of 2 customer notifications sent today. Frequency policy compliant.',
      },
      {
        id: 'rule_4',
        ruleName: 'Payment Instrument Eligibility',
        description: 'Card / Mandate gateway compliance check',
        status: 'passed',
        detail: 'ICICI Corporate E-Mandate is verified active and eligible for recurring presentation.',
      },
    ],
  },
  {
    id: 'pay_7B2eM41p',
    amount: 82500,
    currency: 'INR',
    customer: {
      customerId: 'cust_Grw4812',
      customerName: 'Priya Mehta',
      email: 'priya.mehta@acmecustomer.com',
      segment: 'Growth',
      lifetimeValue: 1260000,
      totalSuccessfulPayments: 48,
      totalFailedPayments: 2,
      historicalRecoveryRate: 0.84,
      avgRecoveryLatencyHours: 1.5,
      retryFatigueScore: 0.8,
    },
    paymentMethod: 'card',
    paymentMethodDetails: 'HDFC Corporate Visa •••• 4421',
    failureReason: 'technical_glitch',
    failureCode: 'ERR_GATEWAY_TIMEOUT_504',
    failedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    recoveryProbability: 0.94,
    expectedRecoveryValue: 77550,
    recommendedAction: 'retry_now',
    priority: 'high',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'Transient issuer timeout detected during momentary HDFC network spike. Immediate retry has 94% expected success with near-zero customer friction.',
    candidateActions: [
      {
        action: 'retry_now',
        label: 'Retry Now (Immediate)',
        probability: 0.94,
        expectedRecovery: 77550,
        confidence: 0.96,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Gateway telemetry confirms HDFC endpoint restored to nominal latency (120ms).',
      },
      {
        action: 'retry_later',
        label: 'Retry Later (2 hrs)',
        probability: 0.85,
        expectedRecovery: 70125,
        confidence: 0.88,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Unnecessary delay since transient gateway fault has already resolved.',
      },
      {
        action: 'send_payment_link',
        label: 'Send Payment Link',
        probability: 0.60,
        expectedRecovery: 49500,
        confidence: 0.80,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Higher friction than seamless backend retry.',
      },
      {
        action: 'stop_recovery',
        label: 'Stop Recovery',
        probability: 0.0,
        expectedRecovery: 0,
        confidence: 0.99,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Rejected: Highly recoverable technical glitch.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Retry Threshold Limit',
        description: 'Maximum permitted retries per cycle',
        status: 'passed',
        detail: '0 of 3 retries used.',
      },
      {
        id: 'rule_2',
        ruleName: 'Gateway Health Check',
        description: 'Issuer latency and availability verification',
        status: 'passed',
        detail: 'HDFC Card acquiring channel operating normally.',
      },
      {
        id: 'rule_3',
        ruleName: 'Recovery Window Active',
        description: '72-hour maximum active recovery period',
        status: 'passed',
        detail: '12 minutes elapsed since decline.',
      },
    ],
  },
  {
    id: 'pay_3K9vT82w',
    amount: 64000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Smb1049',
      customerName: 'Arjun Patel',
      email: 'arjun.patel@gmail.com',
      segment: 'SMB',
      lifetimeValue: 780000,
      totalSuccessfulPayments: 24,
      totalFailedPayments: 5,
      historicalRecoveryRate: 0.68,
      avgRecoveryLatencyHours: 12,
      retryFatigueScore: 3.4,
    },
    paymentMethod: 'upi',
    paymentMethodDetails: 'arjunpatel@okhdfcbank',
    failureReason: 'limit_exceeded',
    failureCode: 'ERR_UPI_MAX_AMOUNT_LIMIT',
    failedAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    recoveryProbability: 0.76,
    expectedRecoveryValue: 48640,
    recommendedAction: 'send_payment_link',
    priority: 'high',
    status: 'at_risk',
    retryCount: 1,
    maxRetriesAllowed: 2,
    aiExplanation: 'Exceeded per-transaction NPCI limit for standard UPI handle. Direct UPI retries will continually fail (0% prob). Generating an instant multi-rail payment link (NetBanking/Cards) yields 76% recovery.',
    candidateActions: [
      {
        action: 'send_payment_link',
        label: 'Send Multi-Rail Payment Link',
        probability: 0.76,
        expectedRecovery: 48640,
        confidence: 0.90,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Allows customer to complete ₹64,000 transaction via NetBanking or Corporate Card.',
      },
      {
        action: 'retry_now',
        label: 'Retry Now (UPI)',
        probability: 0.02,
        expectedRecovery: 1280,
        confidence: 0.98,
        isRecommended: false,
        policyStatus: 'blocked',
        policyNotes: 'Blocked by policy: Static retry will trigger guaranteed NPCI limit decline.',
      },
      {
        action: 'retry_later',
        label: 'Retry Later (UPI)',
        probability: 0.05,
        expectedRecovery: 3200,
        confidence: 0.95,
        isRecommended: false,
        policyStatus: 'blocked',
        policyNotes: 'Blocked: Daily UPI limit will not reset until next calendar day.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Instrument Limit Check',
        description: 'Enforces NPCI UPI per-transaction ceilings',
        status: 'warning',
        detail: 'UPI Auto-Retry disabled due to amount ₹64,000 exceeding standard UPI threshold.',
      },
      {
        id: 'rule_2',
        ruleName: 'Payment Link Multi-Rail Enabled',
        description: 'Verifies fallback checkout rails',
        status: 'passed',
        detail: 'NetBanking, Corporate Cards, and NEFT/RTGS enabled on generated link.',
      },
    ],
  },
  {
    id: 'pay_1M4qX90z',
    amount: 52000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent3901',
      customerName: 'Neha Kapoor',
      email: 'neha.kapoor@gmail.com',
      segment: 'Enterprise',
      lifetimeValue: 5200000,
      totalSuccessfulPayments: 180,
      totalFailedPayments: 1,
      historicalRecoveryRate: 0.96,
      avgRecoveryLatencyHours: 2.0,
      retryFatigueScore: 0.2,
    },
    paymentMethod: 'card',
    paymentMethodDetails: 'Axis Bank Master •••• 8192',
    failureReason: 'card_expired',
    failureCode: 'ERR_EXPIRED_CARD_54',
    failedAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    recoveryProbability: 0.81,
    expectedRecoveryValue: 42120,
    recommendedAction: 'request_payment_method_update',
    priority: 'high',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 1,
    aiExplanation: 'Card validity expired on 08/26. Retrying the existing card is strictly blocked by policy. Automated card-updater link dispatched to the authorized finance controller yields 81% expected recovery.',
    candidateActions: [
      {
        action: 'request_payment_method_update',
        label: 'Request Payment Method Update',
        probability: 0.81,
        expectedRecovery: 42120,
        confidence: 0.92,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Directs user to secure self-serve card update portal with RBI tokenization.',
      },
      {
        action: 'send_payment_link',
        label: 'Send Single-Use Payment Link',
        probability: 0.70,
        expectedRecovery: 36400,
        confidence: 0.85,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Solves immediate invoice but does not update recurring mandate.',
      },
      {
        action: 'retry_now',
        label: 'Retry Now',
        probability: 0.0,
        expectedRecovery: 0,
        confidence: 0.99,
        isRecommended: false,
        policyStatus: 'blocked',
        policyNotes: 'Strictly blocked by policy: Expired card cannot be re-presented.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Expired Instrument Presentation Policy',
        description: 'Card network and RBI tokenization compliance',
        status: 'passed',
        detail: 'Direct retries automatically suppressed for expired card token.',
      },
      {
        id: 'rule_2',
        ruleName: 'RBI Tokenization Self-Serve Active',
        description: 'Secure co-badged tokenization flow',
        status: 'passed',
        detail: 'Token update workflow certified compliant.',
      },
    ],
  },
  {
    id: 'pay_6N1pL38y',
    amount: 47500,
    currency: 'INR',
    customer: {
      customerId: 'cust_Grw9921',
      customerName: 'Vikram Malhotra',
      email: 'accounts@practo.com',
      segment: 'Growth',
      lifetimeValue: 2100000,
      totalSuccessfulPayments: 62,
      totalFailedPayments: 3,
      historicalRecoveryRate: 0.79,
      avgRecoveryLatencyHours: 8.0,
      retryFatigueScore: 2.1,
    },
    paymentMethod: 'mandate',
    paymentMethodDetails: 'SBI E-Mandate •••• 1092',
    failureReason: 'mandate_invalid',
    failureCode: 'ERR_MANDATE_FREQUENCY_LIMIT',
    failedAt: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    recoveryProbability: 0.72,
    expectedRecoveryValue: 34200,
    recommendedAction: 'send_payment_link',
    priority: 'medium',
    status: 'at_risk',
    retryCount: 1,
    maxRetriesAllowed: 2,
    aiExplanation: 'Monthly mandate frequency limit exceeded on SBI account. Automated smart payment link sent to accounts department offers 72% expected value recovery.',
    candidateActions: [
      {
        action: 'send_payment_link',
        label: 'Send On-Demand Payment Link',
        probability: 0.72,
        expectedRecovery: 34200,
        confidence: 0.88,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Allows instant clearing without mandate debit restriction.',
      },
      {
        action: 'retry_later',
        label: 'Retry in Next Billing Cycle',
        probability: 0.50,
        expectedRecovery: 23750,
        confidence: 0.82,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Suboptimal: Causes 28-day cash flow delay.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Mandate Frequency Compliance',
        description: 'Enforces bank debit frequency constraints',
        status: 'passed',
        detail: 'Direct debit suppressed; payment link fallback authorized.',
      },
    ],
  },
  {
    id: 'pay_8V5tU23b',
    amount: 210000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent8831',
      customerName: 'Ananya Sen',
      email: 'finance-lead@licious.com',
      segment: 'Enterprise',
      lifetimeValue: 9400000,
      totalSuccessfulPayments: 310,
      totalFailedPayments: 8,
      historicalRecoveryRate: 0.94,
      avgRecoveryLatencyHours: 3.2,
      retryFatigueScore: 0.9,
    },
    paymentMethod: 'netbanking',
    paymentMethodDetails: 'HDFC Corporate NetBanking',
    failureReason: 'auth_timeout',
    failureCode: 'ERR_2FA_SESSION_EXPIRED',
    failedAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    recoveryProbability: 0.85,
    expectedRecoveryValue: 178500,
    recommendedAction: 'escalate_to_human',
    priority: 'critical',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 2,
    aiExplanation: 'High-ticket Enterprise transaction (>₹2 Lakhs) encountered session timeout during corporate 2FA maker-checker workflow. Escalate directly to Account Relationship Manager with pre-authorized re-authentication trigger.',
    candidateActions: [
      {
        action: 'escalate_to_human',
        label: 'Escalate to Dedicated RM',
        probability: 0.85,
        expectedRecovery: 178500,
        confidence: 0.93,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'VIP priority queue: Account Relationship Manager dispatched via CRM alert.',
      },
      {
        action: 'send_payment_link',
        label: 'Send VIP Payment Link',
        probability: 0.74,
        expectedRecovery: 155400,
        confidence: 0.87,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Direct link to Treasury Corporate Portal.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'VIP Account SLA Check',
        description: 'Enterprise accounts >₹1L route immediately to high-priority touchpoint',
        status: 'passed',
        detail: 'Escalation policy validated. Account value ₹94L LTV.',
      },
    ],
  },
  {
    id: 'pay_5R3xQ19m',
    amount: 38000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Grw3310',
      customerName: 'Rohan Iyer',
      email: 'rohan.iyer@acmecustomer.co',
      segment: 'Growth',
      lifetimeValue: 1840000,
      totalSuccessfulPayments: 74,
      totalFailedPayments: 6,
      historicalRecoveryRate: 0.76,
      avgRecoveryLatencyHours: 6.0,
      retryFatigueScore: 1.8,
    },
    paymentMethod: 'upi',
    paymentMethodDetails: 'rohaniyer@icici',
    failureReason: 'customer_dropoff',
    failureCode: 'ERR_USER_ABANDONED_APP',
    failedAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    recoveryProbability: 0.74,
    expectedRecoveryValue: 28120,
    recommendedAction: 'send_reminder',
    priority: 'medium',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'User navigated away from UPI intent screen before completing PIN entry. WhatsApp notification with 1-click deeplink prompt achieves 74% conversion when sent within 60 minutes.',
    candidateActions: [
      {
        action: 'send_reminder',
        label: 'Send WhatsApp & Push Reminder',
        probability: 0.74,
        expectedRecovery: 28120,
        confidence: 0.89,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Dispatches reminder with UPI deep-link directly into mobile client.',
      },
      {
        action: 'retry_later',
        label: 'Retry via Auto-Debit',
        probability: 0.40,
        expectedRecovery: 15200,
        confidence: 0.81,
        isRecommended: false,
        policyStatus: 'satisfied',
        policyNotes: 'Customer must approve mandate before intent completes.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Drop-off Window Timing',
        description: 'Reminders must be dispatched within 2 hours of abandonment',
        status: 'passed',
        detail: 'Dispatched 50 minutes post dropoff; peak customer engagement window.',
      },
    ],
  },
  {
    id: 'pay_2W8kP74r',
    amount: 9500,
    currency: 'INR',
    customer: {
      customerId: 'cust_Rtl0092',
      customerName: 'Pooja Hegde',
      email: 'qa-tester@rzp-sandbox.in',
      segment: 'Retail',
      lifetimeValue: 45000,
      totalSuccessfulPayments: 3,
      totalFailedPayments: 18,
      historicalRecoveryRate: 0.12,
      avgRecoveryLatencyHours: 48,
      retryFatigueScore: 8.9,
    },
    paymentMethod: 'card',
    paymentMethodDetails: 'Kotak Debit •••• 1120',
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_CARD_REPORTED_STOLEN_43',
    failedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    recoveryProbability: 0.05,
    expectedRecoveryValue: 475,
    recommendedAction: 'stop_recovery',
    priority: 'low',
    status: 'abandoned',
    retryCount: 3,
    maxRetriesAllowed: 3,
    aiExplanation: 'Card instrument reported stolen and retry quota exhausted. Continuous retries will trigger acquirer scheme penalties. Terminate recovery workflow immediately.',
    candidateActions: [
      {
        action: 'stop_recovery',
        label: 'Stop Recovery (Abandon)',
        probability: 0.0,
        expectedRecovery: 0,
        confidence: 0.99,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Terminal fraud code. Halting presentation protects merchant rating.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Fraud / Stolen Card Gate',
        description: 'Hard stop on stolen/lost decline codes',
        status: 'passed',
        detail: 'Enforced hard stop. Presentation locked.',
      },
    ],
  },
  {
    id: 'pay_4C8mN15v',
    amount: 320000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent7701',
      customerName: 'Kabir Singhania',
      email: 'kabir.singhania@acme-client.in',
      segment: 'Enterprise',
      lifetimeValue: 14200000,
      totalSuccessfulPayments: 420,
      totalFailedPayments: 7,
      historicalRecoveryRate: 0.95,
      avgRecoveryLatencyHours: 3.0,
      retryFatigueScore: 0.4,
    },
    paymentMethod: 'mandate',
    paymentMethodDetails: 'Axis Corporate NACH •••• 7712',
    failureReason: 'technical_glitch',
    failureCode: 'ERR_NPCI_NACH_CLEARING_HALT',
    failedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    recoveryProbability: 0.96,
    expectedRecoveryValue: 307200,
    recommendedAction: 'retry_now',
    priority: 'critical',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'NPCI overnight batch synchronization returned momentary gateway clearing error. Acquirer connectivity restored to 100% capacity. Immediate presentation will clear full amount.',
    candidateActions: [
      {
        action: 'retry_now',
        label: 'Retry Now (Immediate Clearing)',
        probability: 0.96,
        expectedRecovery: 307200,
        confidence: 0.98,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'NACH rail verified online by NPCI status feed.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Acquirer Health Monitor',
        description: 'Direct presentation allowed upon rail uptime verification',
        status: 'passed',
        detail: 'Axis Bank NACH gateway operational with 99.98% throughput.',
      },
    ],
  },
  {
    id: 'pay_5D9kP88w',
    amount: 19500,
    currency: 'INR',
    customer: {
      customerId: 'cust_Smb6412',
      customerName: 'Sanjay Verma',
      email: 'billing@chaipoint.in',
      segment: 'SMB',
      lifetimeValue: 640000,
      totalSuccessfulPayments: 38,
      totalFailedPayments: 3,
      historicalRecoveryRate: 0.82,
      avgRecoveryLatencyHours: 5.0,
      retryFatigueScore: 1.1,
    },
    paymentMethod: 'upi',
    paymentMethodDetails: 'chaipoint@axl',
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    failedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    recoveryProbability: 0.86,
    expectedRecoveryValue: 16770,
    recommendedAction: 'retry_later',
    priority: 'medium',
    status: 'recovering',
    retryCount: 1,
    maxRetriesAllowed: 3,
    aiExplanation: 'Daily POS revenue sweep occurs at 18:00 IST for Chai Point franchises. Scheduling automatic debit for 18:30 IST delivers an 86% empirical recovery probability.',
    candidateActions: [
      {
        action: 'retry_later',
        label: 'Retry at Daily Sweep (18:30 IST)',
        probability: 0.86,
        expectedRecovery: 16770,
        confidence: 0.92,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Aligned with merchant daily end-of-day balance replenishment.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Time-of-Day Policy',
        description: 'Auto-retries must target validated liquid windows',
        status: 'passed',
        detail: 'Scheduled for 18:30 IST.',
      },
    ],
  },
  {
    id: 'pay_7J4rT62a',
    amount: 78000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Grw8219',
      customerName: 'Aditi Rao',
      email: 'aditi.rao@gmail.com',
      segment: 'Growth',
      lifetimeValue: 3150000,
      totalSuccessfulPayments: 112,
      totalFailedPayments: 5,
      historicalRecoveryRate: 0.91,
      avgRecoveryLatencyHours: 2.5,
      retryFatigueScore: 0.7,
    },
    paymentMethod: 'card',
    paymentMethodDetails: 'HDFC Corporate Master •••• 9923',
    failureReason: 'auth_timeout',
    failureCode: 'ERR_OTP_VERIFICATION_TIMEOUT',
    failedAt: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    recoveryProbability: 0.89,
    expectedRecoveryValue: 69420,
    recommendedAction: 'send_payment_link',
    priority: 'high',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 2,
    aiExplanation: '3DS OTP timed out on mobile controller. Multi-rail payment link generated with SMS/Email alerts to secondary authorized signatory provides immediate checkout.',
    candidateActions: [
      {
        action: 'send_payment_link',
        label: 'Send Dual-Signatory Link',
        probability: 0.89,
        expectedRecovery: 69420,
        confidence: 0.91,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Enables rapid 2FA completion on both desktop and mobile.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Multi-Factor Re-authentication Policy',
        description: 'RBI guidelines for card 2FA recovery links',
        status: 'passed',
        detail: 'RBI Tokenization & 3DS2 compliant.',
      },
    ],
  },
  {
    id: 'pay_9A1bC23d',
    amount: 115000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent1102',
      customerName: 'Divya Nair',
      email: 'treasury@freshworks.com',
      segment: 'Enterprise',
      lifetimeValue: 8900000,
      totalSuccessfulPayments: 290,
      totalFailedPayments: 3,
      historicalRecoveryRate: 0.97,
      avgRecoveryLatencyHours: 1.8,
      retryFatigueScore: 0.3,
    },
    paymentMethod: 'netbanking',
    paymentMethodDetails: 'Standard Chartered Corporate',
    failureReason: 'technical_glitch',
    failureCode: 'ERR_STAN_CHART_CBS_MAINTENANCE',
    failedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    recoveryProbability: 0.95,
    expectedRecoveryValue: 109250,
    recommendedAction: 'retry_now',
    priority: 'critical',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'Scheduled bank Core Banking System (CBS) weekend maintenance window concluded. Instant retry presentation will settle 100% of outstanding revenue.',
    candidateActions: [
      {
        action: 'retry_now',
        label: 'Retry Now (Post-Maintenance)',
        probability: 0.95,
        expectedRecovery: 109250,
        confidence: 0.97,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Standard Chartered Gateway ping operational (68ms latency).',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Bank Maintenance Tracker',
        description: 'Suppresses retries during reported bank CBS outages',
        status: 'passed',
        detail: 'Outage state resolved.',
      },
    ],
  },
  {
    id: 'pay_2F4eG68h',
    amount: 27500,
    currency: 'INR',
    customer: {
      customerId: 'cust_Smb3019',
      customerName: 'Karan Johar',
      email: 'karan.johar@acmecustomer.co',
      segment: 'SMB',
      lifetimeValue: 420000,
      totalSuccessfulPayments: 19,
      totalFailedPayments: 4,
      historicalRecoveryRate: 0.73,
      avgRecoveryLatencyHours: 14.0,
      retryFatigueScore: 2.8,
    },
    paymentMethod: 'wallet',
    paymentMethodDetails: 'Paytm Business Sub-Wallet',
    failureReason: 'limit_exceeded',
    failureCode: 'ERR_WALLET_BALANCE_EXCEEDED',
    failedAt: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
    recoveryProbability: 0.68,
    expectedRecoveryValue: 18700,
    recommendedAction: 'send_payment_link',
    priority: 'medium',
    status: 'at_risk',
    retryCount: 1,
    maxRetriesAllowed: 2,
    aiExplanation: 'Monthly wallet expenditure ceiling breached. Direct wallet debit blocked. Dispatched multi-rail invoice link with UPI and NetBanking fallback.',
    candidateActions: [
      {
        action: 'send_payment_link',
        label: 'Send Alternate Rail Link',
        probability: 0.68,
        expectedRecovery: 18700,
        confidence: 0.85,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Avoids wallet balance ceiling constraints.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Wallet Policy Limits',
        description: 'Monthly wallet limits enforced on prepaid instruments',
        status: 'passed',
        detail: 'Wallet debit suppressed.',
      },
    ],
  },
  {
    id: 'pay_6H8iJ02k',
    amount: 165000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent4412',
      customerName: 'Ritu Kumar',
      email: 'settlements@shadowfax.in',
      segment: 'Enterprise',
      lifetimeValue: 7200000,
      totalSuccessfulPayments: 240,
      totalFailedPayments: 5,
      historicalRecoveryRate: 0.93,
      avgRecoveryLatencyHours: 3.8,
      retryFatigueScore: 0.6,
    },
    paymentMethod: 'card',
    paymentMethodDetails: 'ICICI Corporate Master •••• 7120',
    failureReason: 'card_expired',
    failureCode: 'ERR_CARD_EXPIRED_TOKEN_54',
    failedAt: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    recoveryProbability: 0.84,
    expectedRecoveryValue: 138600,
    recommendedAction: 'request_payment_method_update',
    priority: 'high',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 2,
    aiExplanation: 'Corporate token expired during end-of-month card renewals. Token updater invitation sent to Finance Controller with biometric authorization.',
    candidateActions: [
      {
        action: 'request_payment_method_update',
        label: 'Request Token Refresh',
        probability: 0.84,
        expectedRecovery: 138600,
        confidence: 0.91,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Directs to RBI-certified token renewal interface.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Expired Token Quarantine',
        description: 'Zero auto-retries on expired card cryptograms',
        status: 'passed',
        detail: 'Quarantine active. Self-service flow provisioned.',
      },
    ],
  },
  {
    id: 'pay_3L5mN79o',
    amount: 54000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Grw2109',
      customerName: 'Manish Malhotra',
      email: 'in-manish.malhotra@acmecustomer.com',
      segment: 'Growth',
      lifetimeValue: 2400000,
      totalSuccessfulPayments: 88,
      totalFailedPayments: 2,
      historicalRecoveryRate: 0.89,
      avgRecoveryLatencyHours: 4.0,
      retryFatigueScore: 0.5,
    },
    paymentMethod: 'mandate',
    paymentMethodDetails: 'HDFC E-Mandate •••• 3410',
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    failedAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    recoveryProbability: 0.87,
    expectedRecoveryValue: 46980,
    recommendedAction: 'retry_later',
    priority: 'high',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'Treasury funds scheduled for incoming wire clearance at 14:00 IST. Delaying presentation by 4 hours yields optimal recovery.',
    candidateActions: [
      {
        action: 'retry_later',
        label: 'Retry Later (4 hrs)',
        probability: 0.87,
        expectedRecovery: 46980,
        confidence: 0.93,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Synchronized with Postman wire receipt window.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Retry Cadence Policy',
        description: 'Enforces minimum 3-hour gap between presentations',
        status: 'passed',
        detail: 'Gap verified.',
      },
    ],
  },
  {
    id: 'pay_8P0qR24s',
    amount: 185000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent6902',
      customerName: 'Gaurav Gupta',
      email: 'b2b-finance@makemytrip.com',
      segment: 'Enterprise',
      lifetimeValue: 11800000,
      totalSuccessfulPayments: 380,
      totalFailedPayments: 4,
      historicalRecoveryRate: 0.96,
      avgRecoveryLatencyHours: 1.5,
      retryFatigueScore: 0.2,
    },
    paymentMethod: 'card',
    paymentMethodDetails: 'Citibank Commercial Visa •••• 5512',
    failureReason: 'technical_glitch',
    failureCode: 'ERR_ACQUIRER_SWITCH_OVERLOAD',
    failedAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    recoveryProbability: 0.95,
    expectedRecoveryValue: 175750,
    recommendedAction: 'retry_now',
    priority: 'critical',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'Temporary load surge on Primary Visa switch. Intelligent fallback routing to secondary Axis acquiring channel will recover transaction immediately.',
    candidateActions: [
      {
        action: 'retry_now',
        label: 'Smart Rail Switch & Retry',
        probability: 0.95,
        expectedRecovery: 175750,
        confidence: 0.96,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Dynamic routing to low-latency acquirer switch.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Dynamic Acquirer Failover',
        description: 'Compliant secondary rail selection',
        status: 'passed',
        detail: 'Secondary acquirer operational.',
      },
    ],
  },
  {
    id: 'pay_1T3uV56w',
    amount: 14200,
    currency: 'INR',
    customer: {
      customerId: 'cust_Smb8910',
      customerName: 'Amitabh Das',
      email: 'accounts@thewholetruthfoods.com',
      segment: 'SMB',
      lifetimeValue: 390000,
      totalSuccessfulPayments: 28,
      totalFailedPayments: 2,
      historicalRecoveryRate: 0.81,
      avgRecoveryLatencyHours: 7.5,
      retryFatigueScore: 1.4,
    },
    paymentMethod: 'upi',
    paymentMethodDetails: 'wholetruth@ybl',
    failureReason: 'customer_dropoff',
    failureCode: 'ERR_APP_SWITCH_TERMINATED',
    failedAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    recoveryProbability: 0.79,
    expectedRecoveryValue: 11218,
    recommendedAction: 'send_reminder',
    priority: 'low',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 2,
    aiExplanation: 'User backgrounded PhonePe app before confirming collect request. Interactive reminder delivered via WhatsApp recovers 79% within 4 hours.',
    candidateActions: [
      {
        action: 'send_reminder',
        label: 'Send Interactive UPI Push',
        probability: 0.79,
        expectedRecovery: 11218,
        confidence: 0.88,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Pre-filled collect request payload.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'User Contact Cadence',
        description: '1 touchpoint in last 12 hours',
        status: 'passed',
        detail: 'Within policy limits.',
      },
    ],
  },
  {
    id: 'pay_4X7yZ91a',
    amount: 98000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Grw7012',
      customerName: 'Meera Joshi',
      email: 'vendorbilling@nykaa.com',
      segment: 'Growth',
      lifetimeValue: 4600000,
      totalSuccessfulPayments: 165,
      totalFailedPayments: 7,
      historicalRecoveryRate: 0.88,
      avgRecoveryLatencyHours: 4.2,
      retryFatigueScore: 1.0,
    },
    paymentMethod: 'mandate',
    paymentMethodDetails: 'Kotak Mahindra E-Mandate •••• 4401',
    failureReason: 'mandate_invalid',
    failureCode: 'ERR_MANDATE_MAX_PER_TXN_EXCEEDED',
    failedAt: new Date(Date.now() - 1000 * 60 * 190).toISOString(),
    recoveryProbability: 0.78,
    expectedRecoveryValue: 76440,
    recommendedAction: 'send_payment_link',
    priority: 'high',
    status: 'at_risk',
    retryCount: 1,
    maxRetriesAllowed: 2,
    aiExplanation: 'Invoice amount of ₹98,000 exceeds mandated limit of ₹50,000. Smart checkout link dispatched for split-free single transaction authorization.',
    candidateActions: [
      {
        action: 'send_payment_link',
        label: 'Send Multi-Tier Invoice Link',
        probability: 0.78,
        expectedRecovery: 76440,
        confidence: 0.89,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Directs to RTGS/NetBanking payment portal.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Mandate Limit Enforcement',
        description: 'Auto-retry suppressed when txn > mandate limit',
        status: 'passed',
        detail: 'Suppression enforced.',
      },
    ],
  },
  {
    id: 'pay_9B3dF57h',
    amount: 450000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent0011',
      customerName: 'Suresh Raina',
      email: 'cloud-accounts@tatadigital.com',
      segment: 'Enterprise',
      lifetimeValue: 28400000,
      totalSuccessfulPayments: 650,
      totalFailedPayments: 6,
      historicalRecoveryRate: 0.98,
      avgRecoveryLatencyHours: 1.2,
      retryFatigueScore: 0.1,
    },
    paymentMethod: 'netbanking',
    paymentMethodDetails: 'SBI Commercial Corporate NetBanking',
    failureReason: 'technical_glitch',
    failureCode: 'ERR_SBI_CORPORATE_PORTAL_TIMEOUT',
    failedAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    recoveryProbability: 0.97,
    expectedRecoveryValue: 436500,
    recommendedAction: 'retry_now',
    priority: 'critical',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'High-value enterprise billing encountered transient SBI gateway network blip. Immediate retry triggered via corporate direct API bridge.',
    candidateActions: [
      {
        action: 'retry_now',
        label: 'Retry via Direct API Gateway',
        probability: 0.97,
        expectedRecovery: 436500,
        confidence: 0.99,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Direct host-to-host bridge verified healthy.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Tier 1 Enterprise VIP Priority',
        description: 'Immediate remediation for accounts >₹1Cr LTV',
        status: 'passed',
        detail: 'VIP policy verified. Zero friction automated retry.',
      },
    ],
  },
  {
    id: 'pay_7K1mO35q',
    amount: 22000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Smb4491',
      customerName: 'Kavita Krishnamurthy',
      email: 'roastery-ops@bluetokaicoffee.com',
      segment: 'SMB',
      lifetimeValue: 580000,
      totalSuccessfulPayments: 44,
      totalFailedPayments: 3,
      historicalRecoveryRate: 0.83,
      avgRecoveryLatencyHours: 6.2,
      retryFatigueScore: 1.2,
    },
    paymentMethod: 'upi',
    paymentMethodDetails: 'bluetokai@hdfcbank',
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    failedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    recoveryProbability: 0.82,
    expectedRecoveryValue: 18040,
    recommendedAction: 'retry_later',
    priority: 'medium',
    status: 'at_risk',
    retryCount: 1,
    maxRetriesAllowed: 3,
    aiExplanation: 'Retail store daily settlement batch clears at 20:00 IST. Automatic retry queued for 20:15 IST delivers 82% expected yield.',
    candidateActions: [
      {
        action: 'retry_later',
        label: 'Retry Post-Settlement (20:15 IST)',
        probability: 0.82,
        expectedRecovery: 18040,
        confidence: 0.90,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Queued for optimal settlement window.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Daily Quota Limit',
        description: 'Max 3 retries per cycle',
        status: 'passed',
        detail: '1 of 3 consumed.',
      },
    ],
  },
  {
    id: 'pay_5S9uW13y',
    amount: 135000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Grw5512',
      customerName: 'Devendra Fadnavis',
      email: 'devendra.fadnavis@acmepartner.in',
      segment: 'Growth',
      lifetimeValue: 5100000,
      totalSuccessfulPayments: 195,
      totalFailedPayments: 5,
      historicalRecoveryRate: 0.90,
      avgRecoveryLatencyHours: 3.5,
      retryFatigueScore: 0.8,
    },
    paymentMethod: 'card',
    paymentMethodDetails: 'Axis Bank Titanium Corporate •••• 1928',
    failureReason: 'auth_timeout',
    failureCode: 'ERR_OTP_NOT_DELIVERED',
    failedAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    recoveryProbability: 0.88,
    expectedRecoveryValue: 118800,
    recommendedAction: 'send_payment_link',
    priority: 'high',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 2,
    aiExplanation: 'Telecom SMS gateway delay prevented OTP reception. Generated multi-factor fallback checkout link supporting WhatsApp OTP and Authenticator Apps.',
    candidateActions: [
      {
        action: 'send_payment_link',
        label: 'Send Multi-Factor Auth Link',
        probability: 0.88,
        expectedRecovery: 118800,
        confidence: 0.92,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Provides fallback 2FA channels to avoid SMS bottlenecks.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: '2FA Channel Diversity',
        description: 'Mandates alternative 2FA when SMS timeouts occur',
        status: 'passed',
        detail: 'WhatsApp & TOTP enabled.',
      },
    ],
  },
  {
    id: 'pay_2Z6bE80d',
    amount: 8500,
    currency: 'INR',
    customer: {
      customerId: 'cust_Rtl9982',
      customerName: 'Sunil Gavaskar',
      email: 'quickbite412@gmail.com',
      segment: 'Retail',
      lifetimeValue: 85000,
      totalSuccessfulPayments: 12,
      totalFailedPayments: 9,
      historicalRecoveryRate: 0.38,
      avgRecoveryLatencyHours: 36,
      retryFatigueScore: 6.5,
    },
    paymentMethod: 'upi',
    paymentMethodDetails: 'quickbite412@paytm',
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    failedAt: new Date(Date.now() - 1000 * 60 * 380).toISOString(),
    recoveryProbability: 0.35,
    expectedRecoveryValue: 2975,
    recommendedAction: 'send_reminder',
    priority: 'low',
    status: 'failed',
    retryCount: 2,
    maxRetriesAllowed: 3,
    aiExplanation: 'Sub-prime recovery probability with elevated retry fatigue score. Send low-frequency reminder with incentive to prevent merchant churn.',
    candidateActions: [
      {
        action: 'send_reminder',
        label: 'Send Gentle Reminder',
        probability: 0.35,
        expectedRecovery: 2975,
        confidence: 0.82,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Prevents customer fatigue while maintaining touchpoint.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Fatigue Suppression',
        description: 'Auto-retries capped when fatigue > 5.0',
        status: 'passed',
        detail: 'Auto-retries suppressed; soft reminder approved.',
      },
    ],
  },
  {
    id: 'pay_4V8xZ02b',
    amount: 260000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Ent9903',
      customerName: 'Sania Mirza',
      email: 'payments@cleartrip.com',
      segment: 'Enterprise',
      lifetimeValue: 16500000,
      totalSuccessfulPayments: 520,
      totalFailedPayments: 4,
      historicalRecoveryRate: 0.96,
      avgRecoveryLatencyHours: 2.1,
      retryFatigueScore: 0.2,
    },
    paymentMethod: 'netbanking',
    paymentMethodDetails: 'Kotak Mahindra Bank Corporate',
    failureReason: 'technical_glitch',
    failureCode: 'ERR_KOTAK_NETBANKING_GATEWAY_502',
    failedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    recoveryProbability: 0.96,
    expectedRecoveryValue: 249600,
    recommendedAction: 'retry_now',
    priority: 'critical',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'Temporary gateway 502 Bad Gateway from Kotak acquirer switch resolved. Re-presenting transaction immediately captures full value.',
    candidateActions: [
      {
        action: 'retry_now',
        label: 'Retry Immediately',
        probability: 0.96,
        expectedRecovery: 249600,
        confidence: 0.97,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Acquirer endpoint returned HTTP 200 OK.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: 'Gateway Restoral Check',
        description: 'Confirms upstream health before re-try',
        status: 'passed',
        detail: 'Latency normal (95ms).',
      },
    ],
  },
  {
    id: 'pay_1C5vB79x',
    amount: 34000,
    currency: 'INR',
    customer: {
      customerId: 'cust_Smb7710',
      customerName: 'Bhaichung Bhutia',
      email: 'finance@epigamia.in',
      segment: 'SMB',
      lifetimeValue: 920000,
      totalSuccessfulPayments: 56,
      totalFailedPayments: 4,
      historicalRecoveryRate: 0.85,
      avgRecoveryLatencyHours: 5.5,
      retryFatigueScore: 1.0,
    },
    paymentMethod: 'mandate',
    paymentMethodDetails: 'ICICI E-Mandate •••• 8821',
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    failedAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    recoveryProbability: 0.84,
    expectedRecoveryValue: 28560,
    recommendedAction: 'retry_later',
    priority: 'medium',
    status: 'at_risk',
    retryCount: 0,
    maxRetriesAllowed: 3,
    aiExplanation: 'Customer receives supplier remittances bi-weekly. Optimal retry window calculated for tomorrow 11:00 IST.',
    candidateActions: [
      {
        action: 'retry_later',
        label: 'Retry Tomorrow at 11:00 IST',
        probability: 0.84,
        expectedRecovery: 28560,
        confidence: 0.91,
        isRecommended: true,
        policyStatus: 'satisfied',
        policyNotes: 'Targets morning banking clearance window.',
      },
    ],
    guardrails: [
      {
        id: 'rule_1',
        ruleName: '72-Hour Active Window',
        description: 'Remaining time: 69.8 hours',
        status: 'passed',
        detail: 'Compliant with policy schedule.',
      },
    ],
  },
];

export const mockDashboardSummary: DashboardSummary = {
  revenueAtRisk: 8420000, // ₹84.20 Lakhs
  predictedRecoverableRevenue: 6315000, // ₹63.15 Lakhs (75% expected value)
  revenueRecovered: 5180000, // ₹51.80 Lakhs (Actual recovered)
  incrementalRevenue: 1840000, // +₹18.40 Lakhs vs standard baseline
  incrementalPercentage: 55.1, // +55.1% incremental lift
  recoveryRate: 0.615, // 61.5% with RecoverIQ
  baselineRecoveryRate: 0.396, // 39.6% with static naive retry
  activeCasesCount: 1420,
  totalCasesProcessed: 6840,
  datasetType: 'synthetic_demo',
  lastUpdated: new Date().toISOString(),
  timeseries: [
    { date: '2026-08-01', label: 'W1 Aug', aiRecovered: 620000, baselineRecovered: 410000, revenueAtRisk: 1050000 },
    { date: '2026-08-08', label: 'W2 Aug', aiRecovered: 1350000, baselineRecovered: 890000, revenueAtRisk: 2200000 },
    { date: '2026-08-15', label: 'W3 Aug', aiRecovered: 2240000, baselineRecovered: 1460000, revenueAtRisk: 3650000 },
    { date: '2026-08-22', label: 'W4 Aug', aiRecovered: 3410000, baselineRecovered: 2210000, revenueAtRisk: 5500000 },
    { date: '2026-08-29', label: 'W5 Aug', aiRecovered: 4520000, baselineRecovered: 2950000, revenueAtRisk: 7200000 },
    { date: '2026-09-02', label: 'Current', aiRecovered: 5180000, baselineRecovered: 3340000, revenueAtRisk: 8420000 },
  ],
  failureBreakdown: [
    {
      reason: 'insufficient_funds',
      label: 'Insufficient Funds',
      revenueAtRisk: 3420000,
      recoveredRevenue: 2360000,
      recoveryRate: 0.69,
      caseCount: 2480,
    },
    {
      reason: 'technical_glitch',
      label: 'Issuer / Gateway Glitch',
      revenueAtRisk: 2150000,
      recoveredRevenue: 1910000,
      recoveryRate: 0.888,
      caseCount: 1620,
    },
    {
      reason: 'auth_timeout',
      label: 'OTP / 3DS Timeout',
      revenueAtRisk: 1240000,
      recoveredRevenue: 640000,
      recoveryRate: 0.516,
      caseCount: 1140,
    },
    {
      reason: 'card_expired',
      label: 'Expired Card',
      revenueAtRisk: 890000,
      recoveredRevenue: 490000,
      recoveryRate: 0.55,
      caseCount: 780,
    },
    {
      reason: 'mandate_invalid',
      label: 'Mandate Limit / Paused',
      revenueAtRisk: 720000,
      recoveredRevenue: 380000,
      recoveryRate: 0.527,
      caseCount: 820,
    },
  ],
  methodBreakdown: [
    {
      method: 'upi',
      label: 'UPI (Auto & Intent)',
      revenueAtRisk: 3620000,
      recoveredRevenue: 2420000,
      recoveryRate: 0.668,
      sharePercent: 43.0,
    },
    {
      method: 'card',
      label: 'Credit & Debit Cards',
      revenueAtRisk: 2840000,
      recoveredRevenue: 1810000,
      recoveryRate: 0.637,
      sharePercent: 33.7,
    },
    {
      method: 'mandate',
      label: 'E-Mandate / Recurring SI',
      revenueAtRisk: 1420000,
      recoveredRevenue: 720000,
      recoveryRate: 0.507,
      sharePercent: 16.9,
    },
    {
      method: 'netbanking',
      label: 'NetBanking',
      revenueAtRisk: 540000,
      recoveredRevenue: 230000,
      recoveryRate: 0.425,
      sharePercent: 6.4,
    },
  ],
  highPriorityCases: mockDetailedPayments,
  recentDecisions: [
    ...mockHistoricalDecisionsList,
    ...mockDetailedPayments.slice(6).map((p, idx) =>
      createDecisionRecordFromPayment(p, {
        id: `dec_${893185 - idx}`,
        executionStatus: idx % 3 === 0 ? 'succeeded' : idx % 3 === 1 ? 'scheduled' : 'pending',
        policyStatus: p.priority === 'critical' ? 'satisfied' : idx === 2 ? 'restricted' : 'satisfied',
        timestamp: new Date(Date.now() - 1000 * 60 * (800 + idx * 120)).toISOString(),
      })
    ),
  ],
};
