import { DecisionRecord, PaymentRecord } from '../types';
import { getAllCanonicalCandidateActions, getStandardPolicyGuardrails, getStructuredDecisionExplanation } from '../utils/recoveryIntelligence';
import { formatActionLabel } from '../utils/formatters';

/**
 * Creates a fully hydrated immutable audit DecisionRecord from a PaymentRecord
 */
export function createDecisionRecordFromPayment(
  payment: PaymentRecord,
  overrides?: Partial<DecisionRecord>
): DecisionRecord {
  const candidateActions = payment.candidateActions || getAllCanonicalCandidateActions(payment);
  const guardrails = payment.guardrails || getStandardPolicyGuardrails(payment);
  const structuredExp = getStructuredDecisionExplanation(payment);
  const isSucceeded = overrides?.executionStatus === 'succeeded';
  const recAmount = isSucceeded ? payment.amount : (overrides?.recoveredAmount ?? 0);

  const passedChecks = guardrails.filter((g) => g.status === 'passed').length;
  const totalChecks = guardrails.length;

  return {
    id: overrides?.id || `dec_${payment.id.replace('pay_', '')}`,
    paymentId: payment.id,
    customerName: payment.customer.customerName,
    customerSegment: payment.customer.segment,
    amount: payment.amount,
    recoveryProbability: payment.recoveryProbability,
    recommendedAction: payment.recommendedAction,
    actionLabel: overrides?.actionLabel || formatActionLabel(payment.recommendedAction),
    expectedRecovery: payment.expectedRecoveryValue,
    policyStatus: overrides?.policyStatus || 'satisfied',
    policyChecksCount: { passed: passedChecks, total: totalChecks },
    executionStatus: overrides?.executionStatus || 'pending',
    recoveredAmount: recAmount,
    modelVersion: overrides?.modelVersion || 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: overrides?.aiExplanationSnippet || payment.aiExplanation || structuredExp.whySelected,
    timestamp: overrides?.timestamp || payment.failedAt,
    failureReason: payment.failureReason,
    failureCode: payment.failureCode,
    paymentMethod: payment.paymentMethod,
    paymentMethodDetails: payment.paymentMethodDetails,
    inputFeatures: {
      customerLTV: payment.customer.lifetimeValue,
      historicalSuccessRate: payment.customer.historicalRecoveryRate,
      retryCount: payment.retryCount,
      maxRetries: payment.maxRetriesAllowed,
      latencyHours: payment.customer.avgRecoveryLatencyHours,
      fatigueScore: payment.customer.retryFatigueScore,
      acquirerState: payment.failureReason === 'technical_glitch' ? '120ms (Restored)' : 'Nominal Acquirer',
    },
    candidateActions,
    guardrails,
    structuredExplanation: {
      whySelected: structuredExp.whySelected,
      importantFactors: structuredExp.importantFactors.map((f) => `${f.title}: ${f.value} — ${f.description}`),
      alternativeTradeoffs: structuredExp.alternativesTradeoffs
        .map((a) => `${a.actionLabel}: EV ${a.expectedValue.toLocaleString('en-IN')} — ${a.rejectionReason}`)
        .join(' | '),
    },
    ...overrides,
  };
}

export const mockHistoricalDecisionsList: DecisionRecord[] = [
  {
    id: 'dec_893201',
    paymentId: 'pay_9F8aK29x',
    customerName: 'Zomato Merchant Ops',
    customerSegment: 'Enterprise',
    amount: 145000,
    recoveryProbability: 0.88,
    recommendedAction: 'retry_later',
    actionLabel: 'Retry Later (Smart Delay)',
    expectedRecovery: 127600,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'scheduled',
    recoveredAmount: 0,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Customer operates on a bimonthly treasury settlement cycle. Scheduled retry timed for 6 hours post-failure, aligning with afternoon liquidity clearing.',
    timestamp: new Date(Date.now() - 1000 * 60 * 4).toISOString(),
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    paymentMethod: 'mandate',
    paymentMethodDetails: 'ICICI Corporate E-Mandate •••• 9012',
    inputFeatures: {
      customerLTV: 3840000,
      historicalSuccessRate: 0.92,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 4.5,
      fatigueScore: 1.2,
      acquirerState: 'Nominal Acquirer (Liquidity Window Peak +6h)',
    },
  },
  {
    id: 'dec_893200',
    paymentId: 'pay_7B2eM41p',
    customerName: 'UrbanPiper CloudTech',
    customerSegment: 'Enterprise',
    amount: 82500,
    recoveryProbability: 0.94,
    recommendedAction: 'retry_now',
    actionLabel: 'Retry Immediately',
    expectedRecovery: 77550,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 82500,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Transient issuer timeout cleared on HDFC channel. Immediate representation succeeded with 100% funds captured on first retry presentation.',
    timestamp: new Date(Date.now() - 1000 * 60 * 11).toISOString(),
    failureReason: 'technical_glitch',
    failureCode: 'ERR_GATEWAY_TIMEOUT_504',
    paymentMethod: 'card',
    paymentMethodDetails: 'HDFC Corporate Visa •••• 4242',
    inputFeatures: {
      customerLTV: 2450000,
      historicalSuccessRate: 0.96,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 1.2,
      fatigueScore: 0.5,
      acquirerState: '120ms Latency (Fully Restored)',
    },
  },
  {
    id: 'dec_893199',
    paymentId: 'pay_5R3xQ19m',
    customerName: 'Swiggy Partner Cloud',
    customerSegment: 'Growth',
    amount: 38000,
    recoveryProbability: 0.74,
    recommendedAction: 'send_reminder',
    actionLabel: 'Send Customer Reminder',
    expectedRecovery: 28120,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'pending',
    recoveredAmount: 0,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Triggered WhatsApp + Email invoice reminder with instant 1-click UPI pay button. Contact frequency rule satisfied (0 of 2 daily notifications sent).',
    timestamp: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    failureReason: 'customer_dropoff',
    failureCode: 'ERR_USER_ABANDONED_CHECKOUT',
    paymentMethod: 'upi',
    paymentMethodDetails: 'swiggycloud@okaxis',
    inputFeatures: {
      customerLTV: 1120000,
      historicalSuccessRate: 0.84,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 6.0,
      fatigueScore: 2.1,
      acquirerState: 'Axis UPI Intent Switch Active',
    },
  },
  {
    id: 'dec_893198',
    paymentId: 'pay_2W8kP74r',
    customerName: 'Razorpay Test Merchant',
    customerSegment: 'Retail',
    amount: 9500,
    recoveryProbability: 0.02,
    recommendedAction: 'stop_recovery',
    actionLabel: 'Stop Recovery (Abandon)',
    expectedRecovery: 190,
    policyStatus: 'blocked',
    policyChecksCount: { passed: 2, total: 4 },
    executionStatus: 'skipped',
    recoveredAmount: 0,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Stolen card decline code (ERR_CARD_STOLEN_43). Deterministic policy strictly blocked further retries to avoid scheme penalty fees and fraud score penalties.',
    timestamp: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
    failureReason: 'card_expired',
    failureCode: 'ERR_CARD_STOLEN_43',
    paymentMethod: 'card',
    paymentMethodDetails: 'Axis Bank Master •••• 1188',
    inputFeatures: {
      customerLTV: 45000,
      historicalSuccessRate: 0.20,
      retryCount: 2,
      maxRetries: 2,
      latencyHours: 48.0,
      fatigueScore: 8.5,
      acquirerState: 'Card Frozen by Issuer Fraud Desk',
    },
  },
  {
    id: 'dec_893197',
    paymentId: 'pay_1M4qX90z',
    customerName: 'Delhivery Logistics Hub 4',
    customerSegment: 'Enterprise',
    amount: 52000,
    recoveryProbability: 0.81,
    recommendedAction: 'request_payment_method_update',
    actionLabel: 'Request Payment Method Update',
    expectedRecovery: 42120,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 52000,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Customer updated corporate card token via RBI compliant self-service link. Recurring auto-debit succeeded with ₹52,000 recovered.',
    timestamp: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    failureReason: 'card_expired',
    failureCode: 'ERR_CARD_EXPIRED_54',
    paymentMethod: 'card',
    paymentMethodDetails: 'Kotak Corporate Credit •••• 5531',
    inputFeatures: {
      customerLTV: 1850000,
      historicalSuccessRate: 0.88,
      retryCount: 1,
      maxRetries: 3,
      latencyHours: 8.4,
      fatigueScore: 2.0,
      acquirerState: 'Tokenization Engine Ready',
    },
  },
  {
    id: 'dec_893196',
    paymentId: 'pay_8V5tU23b',
    customerName: 'Licious Wholesale ColdChain',
    customerSegment: 'Enterprise',
    amount: 210000,
    recoveryProbability: 0.85,
    recommendedAction: 'escalate_to_human',
    actionLabel: 'Escalate to Dedicated RM',
    expectedRecovery: 178500,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'pending',
    recoveredAmount: 0,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Tier-1 Enterprise account (>₹2L invoice size). Policy routed directly to Senior Relationship Manager to prevent high-value merchant friction.',
    timestamp: new Date(Date.now() - 1000 * 60 * 82).toISOString(),
    failureReason: 'limit_exceeded',
    failureCode: 'ERR_TXN_AMOUNT_EXCEEDS_LIMIT',
    paymentMethod: 'upi',
    paymentMethodDetails: 'liciouswholesale@icici',
    inputFeatures: {
      customerLTV: 4950000,
      historicalSuccessRate: 0.94,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 3.0,
      fatigueScore: 0.8,
      acquirerState: 'Corporate NetBanking Link Prepared',
    },
  },
  {
    id: 'dec_893195',
    paymentId: 'pay_3K9vT82w',
    customerName: 'Kalyan Logistics Hub',
    customerSegment: 'SMB',
    amount: 64000,
    recoveryProbability: 0.78,
    recommendedAction: 'send_payment_link',
    actionLabel: 'Send Dynamic Payment Link',
    expectedRecovery: 49920,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 64000,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Transaction exceeded single-rail UPI limit. Dynamic multi-rail link dispatched via WhatsApp allowed customer to complete invoice via NetBanking.',
    timestamp: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    failureReason: 'limit_exceeded',
    failureCode: 'ERR_UPI_MAX_AMOUNT_LIMIT',
    paymentMethod: 'upi',
    paymentMethodDetails: 'kalyanops@okhdfcbank',
    inputFeatures: {
      customerLTV: 780000,
      historicalSuccessRate: 0.68,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 12.0,
      fatigueScore: 3.4,
      acquirerState: 'Multi-rail checkout fallback active',
    },
  },
  {
    id: 'dec_893194',
    paymentId: 'pay_4P1zL67k',
    customerName: 'Dunzo Delivery Fleet HQ',
    customerSegment: 'Enterprise',
    amount: 195000,
    recoveryProbability: 0.89,
    recommendedAction: 'retry_later',
    actionLabel: 'Retry Later (Smart Delay)',
    expectedRecovery: 173550,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 195000,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'E-Mandate liquidity clearing completed successfully on +4h retry window. Total ₹1,95,000 auto-captured.',
    timestamp: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    paymentMethod: 'mandate',
    paymentMethodDetails: 'Axis Corporate E-Mandate •••• 3341',
    inputFeatures: {
      customerLTV: 5200000,
      historicalSuccessRate: 0.91,
      retryCount: 1,
      maxRetries: 3,
      latencyHours: 4.0,
      fatigueScore: 1.0,
      acquirerState: 'Axis Bank Treasury Clearing Nominal',
    },
  },
  {
    id: 'dec_893193',
    paymentId: 'pay_6N7mK32a',
    customerName: 'PharmEasy Supply Distribution',
    customerSegment: 'Enterprise',
    amount: 118000,
    recoveryProbability: 0.92,
    recommendedAction: 'retry_now',
    actionLabel: 'Retry Immediately',
    expectedRecovery: 108560,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 118000,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Network gateway packet drop detected. Retry represented after 180s timeout window captured entire ₹1,18,000 without customer contact.',
    timestamp: new Date(Date.now() - 1000 * 60 * 190).toISOString(),
    failureReason: 'technical_glitch',
    failureCode: 'ERR_ACQUIRER_SWITCH_UNAVAILABLE',
    paymentMethod: 'netbanking',
    paymentMethodDetails: 'SBI Corporate NetBanking •••• 8820',
    inputFeatures: {
      customerLTV: 3600000,
      historicalSuccessRate: 0.95,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 0.8,
      fatigueScore: 0.2,
      acquirerState: 'SBI Switch Back Online (85ms latency)',
    },
  },
  {
    id: 'dec_893192',
    paymentId: 'pay_0B9tY45c',
    customerName: 'Cars24 Inspection Services',
    customerSegment: 'Growth',
    amount: 47500,
    recoveryProbability: 0.65,
    recommendedAction: 'send_payment_link',
    actionLabel: 'Send Dynamic Payment Link',
    expectedRecovery: 30875,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'pending',
    recoveredAmount: 0,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Customer experienced OTP verification timeout on card. Dispatched direct checkout link to registered finance manager.',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    failureReason: 'auth_timeout',
    failureCode: 'ERR_OTP_EXPIRED_TIMEOUT',
    paymentMethod: 'card',
    paymentMethodDetails: 'ICICI Platinum Credit •••• 7712',
    inputFeatures: {
      customerLTV: 940000,
      historicalSuccessRate: 0.79,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 5.2,
      fatigueScore: 1.8,
      acquirerState: 'Payment Link Delivered via WhatsApp Business API',
    },
  },
  {
    id: 'dec_893191',
    paymentId: 'pay_5X2qW89d',
    customerName: 'Zepto DarkStore Infra',
    customerSegment: 'Enterprise',
    amount: 175000,
    recoveryProbability: 0.86,
    recommendedAction: 'retry_later',
    actionLabel: 'Retry Later (Smart Delay)',
    expectedRecovery: 150500,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'scheduled',
    recoveredAmount: 0,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Scheduled representation aligned with early morning NEFT batch cycle (+8h delay).',
    timestamp: new Date(Date.now() - 1000 * 60 * 310).toISOString(),
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    paymentMethod: 'mandate',
    paymentMethodDetails: 'HDFC Corporate Auto-Debit •••• 6610',
    inputFeatures: {
      customerLTV: 4800000,
      historicalSuccessRate: 0.93,
      retryCount: 1,
      maxRetries: 3,
      latencyHours: 6.5,
      fatigueScore: 1.1,
      acquirerState: 'Scheduled Queue: Execution pending',
    },
  },
  {
    id: 'dec_893190',
    paymentId: 'pay_9L3kM18v',
    customerName: 'Blinkit Retail Fulfillment',
    customerSegment: 'Enterprise',
    amount: 132000,
    recoveryProbability: 0.91,
    recommendedAction: 'retry_now',
    actionLabel: 'Retry Immediately',
    expectedRecovery: 120120,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 132000,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'HDFC gateway transient 502 Bad Gateway auto-recovered. Immediate representation settled successfully.',
    timestamp: new Date(Date.now() - 1000 * 60 * 380).toISOString(),
    failureReason: 'technical_glitch',
    failureCode: 'ERR_GATEWAY_TIMEOUT_504',
    paymentMethod: 'card',
    paymentMethodDetails: 'HDFC Diners Black •••• 3001',
    inputFeatures: {
      customerLTV: 3900000,
      historicalSuccessRate: 0.97,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 0.5,
      fatigueScore: 0.1,
      acquirerState: 'Capture Settled HTTP 200',
    },
  },
  {
    id: 'dec_893189',
    paymentId: 'pay_2P4rS90x',
    customerName: 'Meesho Seller Central',
    customerSegment: 'SMB',
    amount: 28500,
    recoveryProbability: 0.70,
    recommendedAction: 'send_payment_link',
    actionLabel: 'Send Dynamic Payment Link',
    expectedRecovery: 19950,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 28500,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Sent multi-rail payment link after UPI mandate failed. Seller completed checkout using credit card.',
    timestamp: new Date(Date.now() - 1000 * 60 * 450).toISOString(),
    failureReason: 'mandate_invalid',
    failureCode: 'ERR_MANDATE_FREQUENCY_MISMATCH',
    paymentMethod: 'mandate',
    paymentMethodDetails: 'Kotak UPI AutoPay •••• 9920',
    inputFeatures: {
      customerLTV: 620000,
      historicalSuccessRate: 0.75,
      retryCount: 1,
      maxRetries: 3,
      latencyHours: 14.0,
      fatigueScore: 2.8,
      acquirerState: 'Payment link paid via Card rail',
    },
  },
  {
    id: 'dec_893188',
    paymentId: 'pay_7Q9wV12t',
    customerName: 'Spinny Auto Retail',
    customerSegment: 'Growth',
    amount: 76000,
    recoveryProbability: 0.83,
    recommendedAction: 'request_payment_method_update',
    actionLabel: 'Request Payment Method Update',
    expectedRecovery: 63080,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'pending',
    recoveredAmount: 0,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Expired card instrument token flagged. Outbound tokenization renewal link delivered to finance lead.',
    timestamp: new Date(Date.now() - 1000 * 60 * 520).toISOString(),
    failureReason: 'card_expired',
    failureCode: 'ERR_CARD_EXPIRED_54',
    paymentMethod: 'card',
    paymentMethodDetails: 'Axis Bank Vistara •••• 8112',
    inputFeatures: {
      customerLTV: 1400000,
      historicalSuccessRate: 0.82,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 10.0,
      fatigueScore: 1.9,
      acquirerState: 'Tokenization workflow initiated',
    },
  },
  {
    id: 'dec_893187',
    paymentId: 'pay_3M8jK54e',
    customerName: 'Nykaa Merchant Logistics',
    customerSegment: 'Enterprise',
    amount: 165000,
    recoveryProbability: 0.87,
    recommendedAction: 'retry_later',
    actionLabel: 'Retry Later (Smart Delay)',
    expectedRecovery: 143550,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 165000,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Scheduled representation at +6h liquidity window resulted in 100% funds capture.',
    timestamp: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    failureReason: 'insufficient_funds',
    failureCode: 'ERR_INSUFFICIENT_FUNDS_51',
    paymentMethod: 'mandate',
    paymentMethodDetails: 'ICICI Corporate NetBanking •••• 4120',
    inputFeatures: {
      customerLTV: 4100000,
      historicalSuccessRate: 0.94,
      retryCount: 1,
      maxRetries: 3,
      latencyHours: 6.0,
      fatigueScore: 0.9,
      acquirerState: 'Automated settlement completed',
    },
  },
  {
    id: 'dec_893186',
    paymentId: 'pay_1R5tP33q',
    customerName: 'PhonePe Merchant Ops',
    customerSegment: 'Enterprise',
    amount: 240000,
    recoveryProbability: 0.88,
    recommendedAction: 'escalate_to_human',
    actionLabel: 'Escalate to Dedicated RM',
    expectedRecovery: 211200,
    policyStatus: 'satisfied',
    policyChecksCount: { passed: 4, total: 4 },
    executionStatus: 'succeeded',
    recoveredAmount: 240000,
    modelVersion: 'RecoverIQ XGB-v2.4.1 (Policy Core)',
    aiExplanationSnippet: 'Dedicated RM contacted merchant treasury head; funds transferred via RTGS with complete invoice settlement.',
    timestamp: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    failureReason: 'limit_exceeded',
    failureCode: 'ERR_RTGS_LIMIT_EXCEPTION',
    paymentMethod: 'netbanking',
    paymentMethodDetails: 'HDFC Corporate RTGS •••• 9901',
    inputFeatures: {
      customerLTV: 6800000,
      historicalSuccessRate: 0.98,
      retryCount: 0,
      maxRetries: 3,
      latencyHours: 2.0,
      fatigueScore: 0.3,
      acquirerState: 'Manual RTGS Confirmation Verified',
    },
  },
];
